app:
  name: "Trump Or Markov Chain?"

server:
  host: "127.0.0.1"
  port: 8080

dataset:
  trump: "../real-data/tweets_01-08-2021.json"
  mobydick: "../real-data/whale.txt"

database:
  # SQLite config
  sqlite: "sqlite:///../data/database.db"
