name: Build

on:
  push:
    branches:
      - "*"

permissions:
  contents: read
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.0

      - name: Install
        run: cd cloud && go mod download

      - name: Build
        run: cd cloud && go build -o ../build/app ./cmd/main.go
